### ISSUE TITLE
Send<TRequestArgs, TResponseArgs>(string, TRequestArgs, Action<TResponseArgs>) fails to convert result to TResponseArgs type

### ISSUE THREAD

**Issue by rcook** [ruidfigueiredo/electron-cgi-dotnet#8]
This is the overload in question:

https://github.com/ruidfigueiredo/electron-cgi-dotnet/blob/75aaccbda30279ebeca89c0a85e29d292200cac5/ElectronCgi.DotNet/Connection.cs#L182

This fails to convert the raw response to `TRequestArgs` due to intermediate conversion via `System.Object`. This leads to errors of the following form:

```
2020-06-12 16:41:17.913 -07:00 [ERR] Failed to run response handler for request with id: 811e5a88-d5cb-480e-ae55-705a2962e4da
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at ElectronCgi.DotNet.Connection.<>c__DisplayClass39_0`2.<SendAsync>b__0(Object arg) in /path/to/ElectronCgi.DotNet/Connection.cs:line 198
   at ElectronCgi.DotNet.ResponseHandler.HandleResponseAsync(Object argument) in /path/to/ElectronCgi.DotNet/IResponseHandler.cs:line 35
   at ElectronCgi.DotNet.ResponseHandlerExecutor.<>c__DisplayClass4_0.<<ExecuteAsync>b__0>d.MoveNext() in /path/to/ElectronCgi.DotNet/ResponseHandlerExecutor.cs:line 43
```

This is a result of `SendAsync` first converting the response to `System.Object` at https://github.com/ruidfigueiredo/electron-cgi-dotnet/blob/75aaccbda30279ebeca89c0a85e29d292200cac5/ElectronCgi.DotNet/Connection.cs#L198 since `SendAsync` is instantiated with `TResponseArgs`=`System.Object`. The handler in `Send` at https://github.com/ruidfigueiredo/electron-cgi-dotnet/blob/75aaccbda30279ebeca89c0a85e29d292200cac5/ElectronCgi.DotNet/Connection.cs#L184 then attempts to convert this `System.Object` instance to the real `TRequestArgs` type using `System.Convert.ChangeType` which fails since `System.Object` does not implement `IConvertible`.

The fix is to instantiate `SendAsync` with the correct `TRequestArgs` type. This bug probably affects other overloads of `Send` and `SendAsync`.

**Comment by ruidfigueiredo** [comment]
Hi @rcook 

Thanks for noticing this and for the pull request! I'll release a new version with the fix probably later today
